spring:
  application:
    name: Authentication-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # use 'validate', 'create', 'create-drop', or 'none' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server.port: 8005
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/docs.html

logging:
  level:
    org.springframework.security: TRACE